using Microsoft.ClearScript.V8;
using Overlayer.Compat.Interface;
using Overlayer.Core;
using Overlayer.Tag.Core;
using System.Text;

namespace Overlayer.V8;

public class V8Manager : IRuntimeService {
    private V8ScriptEngine _engine;
    public V8ScriptEngine Engine => _engine;

    public const string ImplFileName = "impl.js";
    public string ImplFilePath { get; private set; }

    public void Initialize() {
        _engine = new V8ScriptEngine();
        _engine.AddHostObject("TagAccessHelper", new TagAccessHelper());
        ImplFilePath = Path.Combine(MainCore.Paths.JSPath, ImplFileName);
        LoadImplJs();
    }

    public void Reset() {
        _engine?.Dispose();
        _engine = new V8ScriptEngine();
        _engine.AddHostObject("TagAccessHelper", new TagAccessHelper());
        LoadImplJs();
    }

    public void GenerateImplJs() {
        var tags = TagManager.GetAllTags();
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by Overlayer. DO NOT EDIT.");
        sb.AppendLine("");
        sb.AppendLine("if (typeof Tag === 'undefined') {");
        sb.AppendLine("    globalThis.Tag = new Proxy({}, {");
        sb.AppendLine("        get: function(target, prop) {");
        sb.AppendLine("            return function(...args) { return TagAccessHelper.Get(prop, ...args); };");
        sb.AppendLine("        }");
        sb.AppendLine("    });");
        sb.AppendLine("}");

        var sortedTags = tags.OrderBy(t => t.Name);

        foreach(var tag in sortedTags) {
            var paramNames = tag.Parameters.Select(p => p.Name).ToArray();
            string paramList = string.Join(", ", paramNames);

            var jsDocParams = tag.Parameters.Select(p => $"{p.Name}: {MapToJsType(p.ParameterType)}");
            string jsDocParamsStr = string.Join(", ", jsDocParams);

            string returnType = MapToJsType(tag.ReturnType);

            sb.AppendLine("/**");
            if(!string.IsNullOrEmpty(jsDocParamsStr)) {
                sb.AppendLine($" * @param {{{jsDocParamsStr}}}");
            }
            sb.AppendLine($" * @returns {{{returnType}}}");
            sb.AppendLine(" */");
            sb.AppendLine($"if (typeof {tag.Name} === 'undefined') {{");
            sb.AppendLine($"    function {tag.Name}({paramList}) {{ return Tag.{tag.Name}({paramList}); }}");
            sb.AppendLine("}");
        }

        try {
            File.WriteAllText(ImplFilePath, sb.ToString());
            MainCore.Log.Msg($"[{nameof(V8Manager)}] {ImplFileName} generated successfully at: {ImplFilePath}");
        } catch(Exception ex) {
            // 로그 추가: 실패 시
            MainCore.Log.Err($"[{nameof(V8Manager)}] Failed to save {ImplFileName}: {ex.Message}");
        }
    }

    private string MapToJsType(Type type) {
        if(type == typeof(int) || type == typeof(float) || type == typeof(double) || type == typeof(long)) {
            return "number";
        }

        if(type == typeof(string)) {
            return "string";
        }

        if(type == typeof(bool)) {
            return "boolean";
        }

        return "any";
    }

    public void LoadImplJs() {
        string path = ImplFilePath;
        if(File.Exists(path)) {
            try {
                _engine.Execute(File.ReadAllText(path));
            } catch(Exception ex) {
                MainCore.Log.Wrn($"[{nameof(V8Manager)}] Failed to load {ImplFileName}: {ex.Message}");
            }
        }
    }

    public void Dispose() {
        _engine?.Dispose();
    }
}