using Microsoft.ClearScript.V8;
using Overlayer.Compat.Interface;
using Overlayer.Core;
using Overlayer.Tag.Core;
using System.Text;

namespace Overlayer.V8;

public class V8Manager : IRuntimeService {
    public V8ScriptEngine Engine { get; private set; }

    public const string ImplFileName = "impl.js";
    public string ImplFilePath { get; private set; }

    public void Initialize() {
        Engine = new V8ScriptEngine();
        Engine.AddHostObject("TagAccessHelper", new TagAccessHelper());
        ImplFilePath = Path.Combine(MainCore.Paths.JSPath, ImplFileName);
        LoadImplJs();
    }

    public void Reset() {
        Engine?.Dispose();
        Engine = new V8ScriptEngine();
        Engine.AddHostObject("TagAccessHelper", new TagAccessHelper());
        LoadImplJs();
    }

    public void GenerateImplJs() {
        var tags = TagManager.GetAllTags();
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by Overlayer, DO NOT EDIT");
        sb.AppendLine("");
        sb.AppendLine("globalThis.Tag = new Proxy({}, {");
        sb.AppendLine("    get: function(target, prop) {");
        sb.AppendLine("        return function(...args) { return TagAccessHelper.Get(prop, ...args); };");
        sb.AppendLine("    }");
        sb.AppendLine("});");
        sb.AppendLine("");

        var sortedTags = tags.OrderBy(t => t.Name);

        foreach(var tag in sortedTags) {
            var paramNames = tag.Parameters.Select(p => p.Name).ToArray();
            string paramList = string.Join(", ", paramNames);

            var jsDocParams = tag.Parameters.Select(p => $"{p.Name}: {MapToJsType(p.ParameterType)}");
            string jsDocParamsStr = string.Join(", ", jsDocParams);
            string returnType = MapToJsType(tag.ReturnType);

            sb.AppendLine("/**");
            if(!string.IsNullOrEmpty(tag.Description)) {
                string desc = tag.Description.Replace("\n", "\n * ");
                sb.AppendLine($" * {desc}");
            }

            if(!string.IsNullOrEmpty(jsDocParamsStr)) {
                sb.AppendLine($" * @param {{{jsDocParamsStr}}}");
            }
            sb.AppendLine($" * @returns {{{returnType}}}");
            sb.AppendLine(" */");

            sb.AppendLine($"function {tag.Name}({paramList}) {{ return Tag.{tag.Name}({paramList}); }}");
        }

        try {
            File.WriteAllText(ImplFilePath, sb.ToString());
            MainCore.Log.Msg($"[{nameof(V8Manager)}] {ImplFileName} generated successfully at: {ImplFilePath}");
        } catch(Exception ex) {
            MainCore.Log.Err($"[{nameof(V8Manager)}] Failed to save {ImplFileName}: {ex.Message}");
        }
    }

    private string MapToJsType(Type type) {
        if(type == typeof(int) || type == typeof(float) || type == typeof(double) || type == typeof(long) ||
            type == typeof(byte) || type == typeof(short) || type == typeof(uint) || type == typeof(ulong) ||
            type == typeof(ushort) || type == typeof(decimal)) {
            return "number";
        }

        if(type == typeof(string) || type.IsEnum) {
            return "string";
        }

        if(type == typeof(bool)) {
            return "boolean";
        }

        return "any";
    }

    public void LoadImplJs() {
        string path = ImplFilePath;
        if(File.Exists(path)) {
            try {
                Engine.Execute(File.ReadAllText(path));
            } catch(Exception ex) {
                MainCore.Log.Wrn($"[{nameof(V8Manager)}] Failed to load {ImplFileName}: {ex.Message}");
            }
        }
    }

    public void Dispose() => Engine?.Dispose();
}