using Microsoft.ClearScript.V8;
using Overlayer.Compat.Interface;
using Overlayer.Core;
using Overlayer.Tag.Core;
using Overlayer.Tag.Runtime;
using Overlayer.V8.Scripting.Diagnostic;
using Overlayer.V8.Scripting.Tag;
using System.Text;

namespace Overlayer.V8;

public class V8Manager : IRuntimeService {
    private readonly object _engineLock = new();
    private V8ScriptEngine _engine;

    private readonly JSScriptLoader _scriptLoader = new();
    public IReadOnlyList<JSDiagnostic> LoaderDiagnostics => _scriptLoader.Diagnostics;

    public Task InitializationTask { get; private set; }
    private FileSystemWatcher _watcher;

    public const string ImplFileName = "impl.js";
    public const string ScriptFolderName = "Script";

    public string ScriptFolderPath { get; private set; }
    public string ImplFilePath { get; private set; }

    public V8ScriptEngine Engine {
        get {
            lock(_engineLock) {
                return _engine;
            }
        }
    }

    public void Initialize() => InitializationTask = InitializeAsync();

    public async Task InitializeAsync() {
        ImplFilePath = Path.Combine(MainCore.Paths.JSPath, ImplFileName);
        ScriptFolderPath = Path.Combine(MainCore.Paths.JSPath, ScriptFolderName);

        if(!Directory.Exists(ScriptFolderPath)) {
            Directory.CreateDirectory(ScriptFolderPath);
            MainCore.Log.Msg($"[{nameof(V8Manager)}] Script folder created at: {ScriptFolderPath}");
        }

        lock(_engineLock) {
            _engine = new V8ScriptEngine();
            BindEngine(_engine);
        }

        await ExecuteAllScriptsInEngine();

        GenerateImplJs(force: true);
        UpdateWatcher();
    }

    private void BindEngine(V8ScriptEngine engine) => engine.AddHostObject(nameof(TagAccessHelper), new TagAccessHelper());

    private async Task ExecuteAllScriptsInEngine() {
        var files = Directory.GetFiles(ScriptFolderPath, "*.js");
        lock(_engineLock) {
            foreach(var file in files) {
                try {
                    var host = new JSTagRegistrationHost(_scriptLoader, file);
                    _engine.AddHostObject("RegisterTag", (Action<string, object, object>)host.RegisterTag);
                    _engine.Execute(File.ReadAllText(file));
                } catch(Exception e) {
                    MainCore.Log.Err($"[{nameof(V8Manager)}] Script execution error in '{Path.GetFileName(file)}': {e}");
                }
            }

            _engine.Execute("delete globalThis.RegisterTag;");
        }
    }

    public void Reset() {
        lock(_engineLock) {
            _engine?.Dispose();
            _engine = new V8ScriptEngine();
            _engine.AddHostObject("TagAccessHelper", new TagAccessHelper());
        }
        LoadImplJs();
    }

    public async Task ReloadScriptsAsync() {
        lock(_engineLock) {
            _engine.Dispose();
            _engine = new V8ScriptEngine();
            BindEngine(_engine);
        }

        TagCache.Instance.Clear();

        if(await _scriptLoader.LoadAllScriptsAsync(ScriptFolderPath, _engine)) {
            foreach(var diag in LoaderDiagnostics) {
                MainCore.Log.Msg(diag.ToString());
            }
            GenerateImplJs(false);
        }
    }

    public void GenerateImplJs(bool force = false) {
        var content = BuildImplJsContent(TagManager.GetAllTags());

        lock(_engineLock) {
            try {
                if(!force && File.Exists(ImplFilePath)) {
                    string existingContent = File.ReadAllText(ImplFilePath);

                    if(existingContent == content) {
                        _engine.Execute(content);
                        return;
                    }
                }

                File.WriteAllText(ImplFilePath, content);
                _engine.Execute(content);
                MainCore.Log.Msg($"[{nameof(V8Manager)}] {ImplFileName} changed, synced and loaded.");
            } catch(Exception ex) {
                MainCore.Log.Err($"[{nameof(V8Manager)}] Failed to sync {ImplFileName}: {ex.Message}");
            }
        }
    }

    private string BuildImplJsContent(IEnumerable<TagCore> tags) {
        var sb = new StringBuilder();
        sb.AppendLine("/* Auto-generated by Overlayer, DO NOT EDIT */\n");
        sb.AppendLine("globalThis.Tag = new Proxy({}, {");
        sb.AppendLine("    get: function(target, prop) {");
        sb.AppendLine("        return function(...args) { return TagAccessHelper.Get(prop, ...args); };");
        sb.AppendLine("    }");
        sb.AppendLine("});\n");

        sb.AppendLine("/* Overlayer Functions */\n");

        sb.AppendLine("/**");
        sb.AppendLine(" * Registers a new custom tag with the Overlayer engine.");
        sb.AppendLine(" * ");
        sb.AppendLine(" * @param {string} name - The unique name of the tag.");
        sb.AppendLine(" * @param {Function} func - The logic to execute.");
        sb.AppendLine(" * @param {Object} options - Configuration object.");
        sb.AppendLine(" * @param {string[]} options.Params - List of parameter names (e.g., ['time', 'val?']). REQUIRED.");
        sb.AppendLine(" * @param {number} [options.Type] - TagType bitmask for engine behaviors.");
        sb.AppendLine(" * @param {string} [options.Desc] - Description of the tag.");
        sb.AppendLine(" */");
        sb.AppendLine("globalThis.RegisterTag = function(name, func, options) {};\n");

        sb.AppendLine("/* Tags */\n");

        foreach(var tag in tags.OrderBy(t => t.Name)) {
            var paramNames = tag.Parameters.Select(p => p.Name).ToArray();
            string paramList = string.Join(", ", paramNames);
            string returnType = MapToJsType(tag.ReturnType);

            sb.AppendLine("/**");
            if(!string.IsNullOrEmpty(tag.Description)) {
                sb.AppendLine($" * {tag.Description.Replace("\n", "\n * ")}");
            }

            foreach(var p in tag.Parameters) {
                sb.AppendLine($" * @param {{ {p.Name}: {MapToJsType(p.ParameterType)} }}");
            }

            sb.AppendLine($" * @returns {{{returnType}}} */");
            sb.AppendLine($"function {tag.Name}({paramList}) {{ return Tag.{tag.Name}({paramList}); }}\n");
        }
        return sb.ToString();
    }

    private string MapToJsType(Type type) {
        if(type == typeof(int) || type == typeof(float) || type == typeof(double) || type == typeof(long) ||
            type == typeof(byte) || type == typeof(short) || type == typeof(uint) || type == typeof(ulong) ||
            type == typeof(ushort) || type == typeof(decimal)) {
            return "number";
        }

        if(type == typeof(string) || type.IsEnum) {
            return "string";
        }

        if(type == typeof(bool)) {
            return "boolean";
        }

        return "any";
    }

    public void LoadImplJs() {
        lock(_engineLock) {
            if(File.Exists(ImplFilePath)) {
                try {
                    _engine.Execute(File.ReadAllText(ImplFilePath));
                } catch(Exception ex) {
                    MainCore.Log.Wrn($"[{nameof(V8Manager)}] Load failed: {ex.Message}");
                }
            }
        }
    }

    public void UpdateWatcher() {
        bool enabled = MainCore.Conf.EnableJSScriptWatcher;
        if(enabled && _watcher == null) {
            _watcher = new FileSystemWatcher(ScriptFolderPath, "*.js") {
                NotifyFilter = NotifyFilters.FileName | NotifyFilters.LastWrite
            };
            _watcher.Changed += OnScriptChanged;
            _watcher.EnableRaisingEvents = true;
        } else if(!enabled && _watcher != null) {
            _watcher.EnableRaisingEvents = false;
            _watcher.Dispose();
            _watcher = null;
        }
    }

    private void OnScriptChanged(object sender, FileSystemEventArgs e) => _ = ReloadScriptsAsync();

    public void Dispose() {
        lock(_engineLock) {
            _watcher?.Dispose();
            _engine?.Dispose();
            _engine = null;
        }
    }
}